config/routes.rb
ShakespeareApp::Application.routes.draw do

  root 'plays#index'

  resources :plays
  resources :roles

end

app/models/parser.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'
require 'pry'

class Parser

  def initialize
    f = File.open(Rails.root.join('lib', 'assets', 'julius_caesar.xml').to_s)
    @doc = Nokogiri::XML(f)
    f.close

    find_roles
  end

  def doc
    @doc
  end

  def find_roles
    binding.pry
    @doc.xpath("//PERSONAE//PERSONA").each do |doc_role|
      role = Role.new
      role.name = doc_role.text
      role.save
    end
  end

end

app/models/play.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'

class Play < ActiveRecord::Base
  validates_presence_of :name

  has_many :roles,
    inverse_of: :play,
    dependent: :destroy

  has_attached_file :xml

  attr_reader :doc

  def display_roles
    self.roles.take(10)
  end

  def analyze_and_save
    parse_file
    find_roles
    count_num_scenes
    run_role_stats
    self.save
  end

  def parse_file
    f = File.open(Rails.root.join('lib', 'assets', 'julius_caesar.xml').to_s)
    @doc = Nokogiri::XML(f)
    f.close
  end

  def find_roles
    @doc.xpath("//PERSONAE//PERSONA").each do |doc_role|
      role = Role.new
      role.name = doc_role.text
      self.roles << role
    end
  end

  def count_num_scenes
    self.scene_count = @doc.xpath("//SCENE").count
  end

  def run_role_stats
    self.roles.each do |role|
      role.num_lines
      role.num_scenes
      # role.percent_scenes
      # role.long_speech
    end
  end

end

app/models/role.rb
class Role < ActiveRecord::Base

  belongs_to :play,
    inverse_of: :roles


  def num_lines
    if self.number_of_lines_spoken == nil
      total_line_count = 0
      longest_speech = 0
      self.play.doc.xpath("//SPEECH").each do |speech_doc|
          if speech_doc.xpath("SPEAKER").text ==self.name
            speech_line_count = speech_doc.xpath("LINE").count
            total_line_count += speech_line_count
            longest_speech = speech_line_count if longest_speech < speech_line_count
          end
      end
      self.number_of_lines_spoken = total_line_count
      self.longest_speech = longest_speech
    else
      self.number_of_lines_spoken
    end
  end

  def num_scenes
    if self.number_of_scences_role_appears == nil
      role_scene_count = 1
      self.play.doc.xpath("//SCENE").each do |scene_doc|
      end

     self.number_of_scences_role_appears = role_scene_count
    else
      self.number_of_scences_role_appears
    end
  end

  def percent_scenes
    if self.percent_total_scenes == nil
      self.percent_total_scenes = (self.number_of_scences_role_appears*100.00)/self.play.scene_count
    else
      self.percent_total_scenes
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController<ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @plays = Play.all
    @play = Play.new
  end

  def show
    @play = Play.find(params[:id])
    @roles = @play.roles.order(sort_column + ' ' + sort_direction)
  end

  def create
    @play = Play.new(play_params)
    if @play.analyze_and_save
      flash[:notice] = "Your play has been successfuly created!"
      redirect_to plays_path
    else
      flash[:notice] = "Something went wrong!"
      redirect_to plays_path
    end
  end

  private

  def play_params
    params.require(:play).permit(:name, :xml)
  end

  # helper methods for default sort A-Z on role name
  def sort_column
    Role.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  # sanitizing data to prevent SQL injection. Is direction "asc" or "desc"?
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/plays/index.html.erb
<h1>Hello</h1>

<%= form_for @play, :html => {multipart:true} do |f| %>
  <p>
    <%=f.label :name%> <br>
    <%=f.text_field :name%>
  </p>

  <p>
    <%= f.file_field :xml %>
  </p>

  <p>
    <%=f.submit "Submit" %>
  </p>
<% end %>


<% @plays.each do |play| %>
  <%= link_to play.name, play_path(play) %>
<% end %>

app/views/plays/show.html.erb
<%= @play.name %>

<TABLE class="role-table">
  <tr>
    <th><%= sortable "name", "Role"%>    <i class='fi-arrow-up large'></i>
</th>
    <th><%= sortable "number_of_lines_spoken", "Number of Lines"%></th>
    <th><%= sortable "number_of_scences_role_appears", "Number of Scenes"%></th>
    <th><%= sortable "percent_total_scenes", "Percent Total Scenes"%></th>
    <th><%= sortable "longest_speech", "Longest Speech"%></th>
  </tr>

  <% @roles.each do |role| %>
    <tr>
      <th><%=role.name.titleize%></th>
      <td><%=role.num_lines%></td>
      <td><%=role.num_scenes%></td>
      <td><%=role.percent_scenes.round(2)%>%</td>
      <td><%=role.longest_speech%></td>
    </tr>
  <% end %>

</TABLE>

<br><br><br><br>


The table should show the following
statistics for each role in the play: number of lines spoken, longest
speech, number of scenes in which the role appears, and percent of total
scenes in which the role appears.







<%= link_to 'Back', root_path %>